import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../../core/services/auth_service.dart';
import '../../../models/user_model.dart';

class BrMouAgentAddScreen extends StatefulWidget {
  const BrMouAgentAddScreen({super.key});

  @override
  State<BrMouAgentAddScreen> createState() => _BrMouAgentAddScreenState();
}

class _BrMouAgentAddScreenState extends State<BrMouAgentAddScreen> {
  final _formKey = GlobalKey<FormState>();
  final _nameController = TextEditingController();
  final _companyController = TextEditingController();
  final _lastActiveController = TextEditingController(text: "Aktif sejak ${DateTime.now().year}");

  String _selectedStatus = "Aktif";

  Future<void> _saveAgent() async {
    if (_formKey.currentState!.validate()) {
      final newAgent = AppUser(
        idUser: '', // Auto-generated by Firestore add()
        nama: _nameController.text.trim(),
        email: '${_nameController.text.trim().replaceAll(' ', '').toLowerCase()}@tidaragent.com', // Dummy email for agent user
        role: UserRole.agent,
        noHp: _companyController.text.trim(), // Storing agency in noHp or phone
        status: _selectedStatus,
        createdAt: DateTime.now(),
      );

      final authService = Provider.of<AuthService>(context, listen: false);
      await authService.addAgentUser(newAgent);

      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text("✅ Agent berhasil ditambahkan"), backgroundColor: Colors.green),
      );

      Navigator.pop(context); // Kembali ke halaman list
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text("Tambah Agent MOU")),
      body: Padding(
        padding: const EdgeInsets.all(16),
        child: Form(
          key: _formKey,
          child: SingleChildScrollView(
            child: Column(
              children: [
                TextFormField(
                  controller: _nameController,
                  decoration: const InputDecoration(labelText: "Nama Agent"),
                  validator: (value) => value!.isEmpty ? "Nama tidak boleh kosong" : null,
                ),
                const SizedBox(height: 16),
                TextFormField(
                  controller: _companyController,
                  decoration: const InputDecoration(labelText: "Perusahaan / Agency"),
                  validator: (value) => value!.isEmpty ? "Perusahaan tidak boleh kosong" : null,
                ),
                const SizedBox(height: 16),
                DropdownButtonFormField<String>(
                  value: _selectedStatus,
                  decoration: const InputDecoration(labelText: "Status"),
                  items: const [
                    DropdownMenuItem(value: "Aktif", child: Text("Aktif")),
                    DropdownMenuItem(value: "Nonaktif", child: Text("Nonaktif")),
                  ],
                  onChanged: (value) {
                    setState(() => _selectedStatus = value!);
                  },
                ),
                const SizedBox(height: 16),
                TextFormField(
                  controller: _lastActiveController,
                  decoration: const InputDecoration(labelText: "Keterangan Aktif"),
                ),
                const SizedBox(height: 32),
                SizedBox(
                  width: double.infinity,
                  height: 52,
                  child: ElevatedButton(
                    onPressed: _saveAgent,
                    style: ElevatedButton.styleFrom(
                      backgroundColor: const Color(0xFF1E88E5),
                      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                    ),
                    child: const Text("Simpan Agent", style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold)),
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}