// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2oYgXrTT7LgjfZEgCMQYVFpHX_cJFQi4',
    appId: '1:834592686206:android:279e4d6b31b4011a34d82f',
    messagingSenderId: '834592686206',
    projectId: 'tidar-property-c88ae',
    storageBucket: 'tidar-property-c88ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8aspbOEfjJhx25lQ9iYLS0JYngCOtDYg',
    appId: '1:834592686206:ios:cda33a27d3f3532134d82f',
    messagingSenderId: '834592686206',
    projectId: 'tidar-property-c88ae',
    storageBucket: 'tidar-property-c88ae.firebasestorage.app',
    iosBundleId: 'com.example.tidarProperty',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSZjX5VLu7Sh25g7uyxATFhEY-Vj5syhc',
    appId: '1:834592686206:web:3a6afad705e4db4d34d82f',
    messagingSenderId: '834592686206',
    projectId: 'tidar-property-c88ae',
    authDomain: 'tidar-property-c88ae.firebaseapp.com',
    storageBucket: 'tidar-property-c88ae.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8aspbOEfjJhx25lQ9iYLS0JYngCOtDYg',
    appId: '1:834592686206:ios:cda33a27d3f3532134d82f',
    messagingSenderId: '834592686206',
    projectId: 'tidar-property-c88ae',
    storageBucket: 'tidar-property-c88ae.firebasestorage.app',
    iosBundleId: 'com.example.tidarProperty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSZjX5VLu7Sh25g7uyxATFhEY-Vj5syhc',
    appId: '1:834592686206:web:846c70b69549868434d82f',
    messagingSenderId: '834592686206',
    projectId: 'tidar-property-c88ae',
    authDomain: 'tidar-property-c88ae.firebaseapp.com',
    storageBucket: 'tidar-property-c88ae.firebasestorage.app',
  );

}